version: '3'
services:
  db:
    container_name: diagnoscat-db
    image: mysql:5.7
    volumes:
      - .data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'database'
